# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: development_e_shop
  username: username
  password: password
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: test_e_shop
  username: username
  password: password
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: e_shop
  username: username
  password: password
  host: localhost
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
